[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Build completed - LinkTree Dinâmico'"

[functions]
  directory = "netlify/functions"

# Redirects e rewrites
[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/public"
  to = "/public.html"
  status = 200

[[redirects]]
  from = "/links"
  to = "/public.html"
  status = 200

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para a API
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"

# Cache para assets estáticos
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Configurações de environment (opcional)
[build.environment]
  NODE_VERSION = "18"

# Context-specific settings
[context.production]
  command = "echo 'Production build - LinkTree Dinâmico'"

[context.deploy-preview]
  command = "echo 'Deploy preview build'"

[context.branch-deploy]
  command = "echo 'Branch deploy build'"